# Generated by Django 5.2.3 on 2025-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
